language: go

go:
  - "1.10.x"

install: true

stages:
  - build
  - markdownlint

jobs:
  include:
    - stage: build
      script:
        - go get -u golang.org/x/lint/golint
        - ./build.sh
    - stage: markdownlint
      script:
        - gem install mdl
        - mdl .
